pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "AndroidAPS"

include ':app'
include ':shared:impl'
include ':core:data'
include ':core:objects'
include ':core:graph'
include ':core:graphview'
include ':core:interfaces'
include ':core:keys'
include ':core:libraries'
include ':core:nssdk'
include ':core:utils'
include ':core:ui'
include ':core:validators'
include ':ui'
include ':plugins:aps'
include ':plugins:automation'
include ':plugins:configuration'
include ':plugins:constraints'
include ':plugins:insulin'
include ':plugins:main'
include ':plugins:sensitivity'
include ':plugins:smoothing'
include ':plugins:source'
include ':plugins:sync'
include ':implementation'
include ':database:impl'
include ':database:persistence'
include ':pump:combov2'
include ':pump:combov2:comboctl' // ← この行を追加
include ':pump:dana'
include ':pump:danars'
include ':pump:danar'
include ':pump:diaconn'
include ':pump:eopatch'
include ':pump:eopatch:core' // ← この行を追加
include ':pump:medtrum'
include ':pump:equil'
include ':pump:insight'
include ':pump:medtronic'
include ':pump:common'
include ':pump:omnipod:common'
include ':pump:omnipod:eros'
include ':pump:omnipod:dash'
include ':pump:rileylink'
include ':pump:virtual'
include ':workflow'
include ':shared:tests'
