name: AAPS-CI
on:
  workflow_dispatch:
    inputs:
      aaps_version:
        description: 'Select AAPS Version'
        required: true
        default: '3.4.2.6'
      build_variant:
        description: 'Select Build Variant'
        required: true
        default: 'fullRelease'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew :aaps:assembleRelease -PskipTests=true
      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: app-full-release
          path: "**/build/outputs/apk/**/*.apk"
