name: AndroidAPS CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean :aaps:assembleFull -PskipTests=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS
          path: "**/build/outputs/apk/**/*.apk"
